-- ============================================================
-- SECTION 7 : ORDER STATUS ANALYSIS
-- Description:
-- This section analyzes order fulfillment performance,
-- cancellation trends, and revenue generated by different
-- order statuses.
-- ============================================================

use amazon_ai_sales_analytics;

-- ------------------------------------------------------------
-- Query 1 : Number of Orders by Order Status
-- Business Question: How many orders are there for each order status?
-- ------------------------------------------------------------
select OrderStatus,count(OrderId) as Number_Of_Orders
from sales_data
group by OrderStatus
order by Number_Of_Orders  desc;

-- ------------------------------------------------------------
-- Query 2 : Revenue by Order Status
-- Business Question: How much revenue has each order status generated?
-- ------------------------------------------------------------
select OrderStatus,sum(TotalAmount) as Total_revenue
from sales_data
group by OrderStatus
order by Total_Revenue desc;

-- ------------------------------------------------------------
-- Query 3 : Average Order Value by Order Status
-- Business Question: What is the average order value for each order status?
-- ------------------------------------------------------------
select OrderStatus, round(avg(TotalAmount),2) as Average_Order_Value
from sales_data
group by OrderStatus
order by Average_Order_Value desc;

-- ------------------------------------------------------------
-- Query 4 : Cancelled Orders
-- Business Question: How many orders have been cancelled?
-- ------------------------------------------------------------
select OrderStatus,count(OrderId) as Number_Of_Orders
from sales_data where OrderStatus="Cancelled";

-- ------------------------------------------------------------
-- Query 5 : Cancellation Rate
-- Business Question: What percentage of total orders were cancelled?
-- ------------------------------------------------------------
select round((count(OrderID) * 100.0) /(select count(*) from sales_data),2) as Cancellation_Rate
from sales_data
where OrderStatus = 'Cancelled';